# Generated by Django 3.1.1 on 2020-12-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=20)),
                ('marks_maximum', models.CharField(max_length=3)),
                ('marks_obtained', models.CharField(max_length=3)),
            ],
        ),
    ]
