# Generated by Django 3.1.1 on 2020-12-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('attendance', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='absentees',
            field=models.ManyToManyField(blank=True, to='users.StudentProfile', verbose_name='absentees'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacherprofile', verbose_name='teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacherprofile', verbose_name='teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together={('conducted_date', 'subject', 'Class')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject')},
        ),
    ]
